### ISSUE TITLE
Provide installation guidelines on linux

### ISSUE THREAD

**Issue by thibautjombart** [richfitz/cyphr#1]
More specifically, I'm selfishly interested in debian-based systems. So far it looks like libsodium-dev is not on standard repos. Compiling from the sources following:
https://download.libsodium.org/doc/installation/index.html

works for me. System:
Linux Swift 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jeroen** [comment]
You might want to check the [sodium package readme](github.com/jeroenooms/sodium#readme).
