### ISSUE TITLE
Mostly comments on the README

### ISSUE THREAD

**Issue by maelle** [richfitz/cyphr#13]
🐨

**Comment by maelle** [comment]
- the alert message is great but maybe say that it means that you can still use the package for a short term transfer?
- if you have a timeline for version 1.0 or a Github milestone link to it.
- in the list of styles of encryption I'd start with the two symmetric ones and then the two with public keys, it'd be more logical in that order.
- "To generate keys, you really should read the underlying documentation in the sodium or openssl packages" add links?
- "Encrypting files like the above risks leaving a cleartext version around. " I know it sounds stupid but re-state what the cleartext version is. It means one has saved blabla.csv on top of the encrypted version.
- "With (probably) some limitations, the argument to the wrapped functions can be connection objects. " Can you give an example of what this would be?
- "Because cyphr::encrypt and cyphr::decrypt compute on the language, standard evaluation forms cyphr::encrypt_ and cyphr::decrypt_ are provided that take a quoted expression as their first argument." doesn't really belong to its subsection?
- "However, there are bound to be more functions that could be useful to add here (e.g., readxl::read_excel). " Isn't one of the two solutions you provide better than the other one?
- At the top of the README and of the website first page, an example of a practical use case would be great (you know just saying someone wants to send something to somebody, just to make it less abstract)
- Typo in "sodium does not support streaming encryption/decrption. "
- Why is the Authors section of the pkgdown website empty?
- "(you're using R, remember)." provide a link e.g. to Bob's and Dirk's package.

**Comment by maelle** [comment]
Also it's still not 100% clear to me after reading the README how to save a key. In the intro vignette if you explain it maybe say it at the beginning ("we will explain later how to save keys")?

**Comment by richfitz** [comment]
Thanks a lot @maelle - super useful
