### ISSUE TITLE
version 1.0.0

### ISSUE THREAD

**Issue by NoushinN** [richfitz/cyphr#24]
Really enjoying this package, working great for my purposes, but notice the warning and somewhat worried. May I know when version 1.0.0 is expected so we expect backward compatibility? thank you!

**Comment by richfitz** [comment]
I just need to write a test! I will try and move on this - please remind me in a month if nothing has happened.

**Comment by richfitz** [comment]
No time like the present - the `develop` branch now has the warning removed and a reference example

**Comment by richfitz** [comment]
OK, version 1.0.0 is sent to CRAN 🤞

**Comment by richfitz** [comment]
Released to CRAN as version `1.0.1`: https://cran.r-project.org/package=cyphr
