### ISSUE TITLE
Can I decrypt string if it was encrypt by PHP blowfish?

### ISSUE THREAD

**Issue by selesnow** [richfitz/cyphr#26]
Hello! Thank for the cyphr.

I have an encrypted string, it was encrypted by PHP.

What i need: Decrypting this string by R

What i have:

```
Encrypted data for test: "atJpjpKSv8SWEVovBE17K/+szAMyoJMC"
Decrypted data for test: "My secret string"
Encryption algoritm:
```

Blowfish
```
cipher: 'bf-cbc'
hashType: 'sha1'
encryptOptions: OPENSSL_ZERO_PADDING|OPENSSL_RAW_DATA;
secretKey: "asdasdni087uiweiuhHJKnoHkasdHUIB"
```

I try some packages: PKI, cyphr, safer But i can't decrypted atJpjpKSv8SWEVovBE17K/+szAMyoJMC to My secret string

I need get `My secret string` from `atJpjpKSv8SWEVovBE17K/+szAMyoJMC`.

**Comment by richfitz** [comment]
I see you have opened this as https://github.com/jeroen/openssl/issues/75 - you'll want to be using the lower level `openssl` functions for this, but the details will depend on how your PHP encryption is storing everything. Good luck
