### ISSUE TITLE
Signature of data does not match

### ISSUE THREAD

**Issue by BlackEdder** [richfitz/cyphr#27]
I am trying to request access to data on another machine. On that machine I did:

```{r}
cyphr::data_request_access(data_dir)
```

And get the expected A request has been added... message. I then switch back to my main machine and try to authorise the request there, but get the following error message:

```{r}
cyphr::data_admin_authorise(data_dir)
Error in value[[3L]](cond) : 
  Signature of data does not match for [key]
```

**Comment by BlackEdder** [comment]
Some more information. Actually when I try to authorise at first it gives:

```{r}
cyphr::data_admin_authorise(data_dir)
Error in FUN(X[[i]], ...) : 
  Public key hash disagrees for: [key]
```

After I run:

```{r}
key <- cyphr::data_key(data_dir)
```

It gives the error I mentioned above: 

```{r}
cyphr::data_admin_authorise(data_dir)
Error in value[[3L]](cond) : 
  Signature of data does not match for: [key]
```

**Comment by richfitz** [comment]
The verification has failed, so this is something to do to with the keys that you have loaded I believe. Can you get the vignette to work for you?
